### ISSUE TITLE
Next release of jce

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/johnnycanencrypt#57]
## Features we want

- [x] Automated db schema upgrade for `KeyStore` #64 
- [ ] Tests for smartcard features #58 
- [ ] Add new subkey 
- [x] Change the expiration date of a subkey
- [ ] Revoke a subkey

- [x] Add new user id #62
- [x] Revoke user id #67 
- [x] Add a table to store jce version
- [x] Change the password of a key #66

**Comment by SaptakS** [comment]
@kushaldas we will also need to add a feature to change passphrases.

**Comment by kushaldas** [comment]
I guess I should just go ahead and make a release.

**Comment by kushaldas** [comment]
We can close this one too.
